### ISSUE TITLE
Responsive class

### ISSUE THREAD

**Issue by dimitri-cua** [kaangokdemir/bulma-spacing#6]
Hello,

Very cool extension for Bulma, very usefull!

Is there a responsive options coming? Like is-mobile, etc. 

Regards,

Dimitri

**Comment by kaangokdemir** [comment]
Thanks for compliments and creating the issue. 

Since version 0.9.0, Bulma has it's own spacing helpers. At the past it was needed to use a third party library with Bulma and this was why I created this package however nowadays it's not. I'm highly recommending to use Bulma's built-in [spacings](https://bulma.io/documentation/helpers/spacing-helpers/): Since my package is zero dependency, responsiveness can't be a feature at there. You should check this [issue](https://github.com/jgthms/bulma/issues/451) and ask responsiveness situation from there.

Best.
